# Generated by Django 4.2.8 on 2024-01-11 16:49
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models

import payments.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reversion", "0002_add_index_on_version_for_content_type_and_db"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system_meta", "0002_add_system_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "integrated_system",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_meta.integratedsystem",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basket",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Fulfilled"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                            ("declined", "Declined"),
                            ("errored", "Errored"),
                            ("review", "Review"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "total_price_paid",
                    models.DecimalField(decimal_places=5, max_digits=20),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "purchaser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(max_length=255, unique=True)),
                ("amount", models.DecimalField(decimal_places=5, max_digits=20)),
                ("data", models.JSONField()),
                (
                    "transaction_type",
                    models.TextField(
                        choices=[("payment", "payment"), ("refund", "refund")],
                        default="payment",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="payments.order",
                    ),
                ),
                (
                    "product_version",
                    models.ForeignKey(
                        limit_choices_to=payments.models.Line._order_line_product_versions,  # noqa: SLF001
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reversion.version",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BasketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basket_items",
                        to="payments.basket",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basket_item",
                        to="system_meta.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CanceledOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments.order",),
        ),
        migrations.CreateModel(
            name="DeclinedOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments.order",),
        ),
        migrations.CreateModel(
            name="ErroredOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments.order",),
        ),
        migrations.CreateModel(
            name="FulfilledOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments.order",),
        ),
        migrations.CreateModel(
            name="PartiallyRefundedOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments.order",),
        ),
        migrations.CreateModel(
            name="PendingOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(payments.models.FulfillableOrder, "payments.order"),
        ),
        migrations.CreateModel(
            name="RefundedOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments.order",),
        ),
        migrations.CreateModel(
            name="ReviewOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(payments.models.FulfillableOrder, "payments.order"),
        ),
        migrations.AddConstraint(
            model_name="line",
            constraint=models.UniqueConstraint(
                fields=("order_id", "product_version_id"),
                name="unique_order_purchased_object",
            ),
        ),
    ]
