# Generated by Django 4.2.9 on 2024-02-08 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_add_order_and_basket_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="integrated_system",
        ),
    ]
