# Generated by Django 4.2.16 on 2024-10-16 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_alter_order_state"),
    ]

    def _delete_existing_baskets(apps, scheme_editor):
        model = apps.get_model("payments", "basket")
        model.objects.all().delete()

    operations = [
        migrations.RunPython(_delete_existing_baskets),
    ]
