# Generated by Django 4.2.16 on 2024-10-16 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system_meta", "0005_integratedsystem_payment_process_redirect_url"),
        ("payments", "0003_alter_order_state"),
    ]

    def _delete_existing_baskets(apps, scheme_editor):
        model = apps.get_model("payments", "basket")
        model.objects.all().delete()

    operations = [
        migrations.AddField(
            model_name="basket",
            name="integrated_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket",
                to="system_meta.integratedsystem",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="basket",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
