# Generated by Django 4.2.16 on 2024-10-28 20:07

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_meta", "0005_integratedsystem_payment_process_redirect_url"),
        ("payments", "0003_alter_order_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("country_code", django_countries.fields.CountryField(max_length=2)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "blocked countries",
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("country_code", django_countries.fields.CountryField(max_length=2)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "tax_rate_name",
                    models.CharField(blank=True, default="VAT", max_length=100),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="basket",
            name="user_country_code",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The country code for the user for this basket.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="user_geolocation_type",
            field=models.CharField(
                choices=[("profile", "profile"), ("geoip", "geoip"), ("none", "none")],
                default="none",
                help_text="How the user's location was determined.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="user_ipv4",
            field=models.CharField(
                blank=True, help_text="The IPv4 address of the user.", max_length=22
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="user_ipv6",
            field=models.CharField(
                blank=True, help_text="The IPv6 address of the user.", max_length=46
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="purchaser_country_code",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The country code for the user for this basket.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="purchaser_geolocation_type",
            field=models.CharField(
                choices=[],
                default="none",
                help_text="How the user's location was determined.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="purchaser_ipv4",
            field=models.CharField(
                blank=True, help_text="The IPv4 address of the user.", max_length=22
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="purchaser_ipv6",
            field=models.CharField(
                blank=True, help_text="The IPv6 address of the user.", max_length=46
            ),
        ),
        migrations.AddConstraint(
            model_name="taxrate",
            constraint=models.UniqueConstraint(
                fields=("country_code",), name="unique_country"
            ),
        ),
        migrations.AddField(
            model_name="blockedcountry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_countries",
                to="system_meta.product",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blockedcountry",
            unique_together={("product", "country_code")},
        ),
    ]
