# Generated by Django 4.2.16 on 2024-10-25 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_meta", "0005_integratedsystem_payment_process_redirect_url"),
        ("payments", "0007_discount_assigned_users_redeemeddiscount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="integrated_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="discounts",
                to="system_meta.integratedsystem",
            ),
        ),
    ]
