# Generated by Django 4.2.16 on 2024-11-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('payments', '0009_bulkdiscountcollection'), ('payments', '0010_alter_bulkdiscountcollection_discounts'), ('payments', '0011_remove_bulkdiscountcollection_discounts_and_more')]

    dependencies = [
        ('payments', '0008_remove_discount_assigned_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDiscountCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='discount',
            name='bulk_discount_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='payments.bulkdiscountcollection'),
        ),
    ]
