# Generated by Django 4.2.16 on 2024-11-04 21:38

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_meta", "0005_integratedsystem_payment_process_redirect_url"),
        ("payments", "0008_remove_discount_assigned_users_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("country_code", django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                "verbose_name_plural": "blocked countries",
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_on",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("country_code", django_countries.fields.CountryField(max_length=2)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=6),
                ),
                (
                    "tax_rate_name",
                    models.CharField(blank=True, default="VAT", max_length=100),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basket",
            name="user_blockable_country_code",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The country code for the user for this basket for blocked items.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="user_blockable_geolocation_type",
            field=models.CharField(
                choices=[],
                default="none",
                help_text="How the user's location was determined for blocked items.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="user_ip",
            field=models.CharField(
                blank=True, help_text="The IP address of the user.", max_length=46
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="user_taxable_country_code",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The country code for the user for this basket for tax purposes.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="user_taxable_geolocation_type",
            field=models.CharField(
                choices=[("profile", "profile"), ("geoip", "geoip"), ("none", "none")],
                default="none",
                help_text="How the user's location was determined for tax purposes.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="purchaser_blockable_country_code",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The country code for the user for this order for blocked items.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="purchaser_blockable_geolocation_type",
            field=models.CharField(
                choices=[],
                default="none",
                help_text="How the user's location was determined for blocked items.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="purchaser_ip",
            field=models.CharField(
                blank=True, help_text="The IP address of the user.", max_length=46
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="purchaser_taxable_country_code",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The country code for the user for this order for tax purposes.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="purchaser_taxable_geolocation_type",
            field=models.CharField(
                choices=[],
                default="none",
                help_text="How the user's location was determined for tax purposes.",
                max_length=15,
            ),
        ),
        migrations.AddConstraint(
            model_name="taxrate",
            constraint=models.UniqueConstraint(
                fields=("country_code",), name="unique_country"
            ),
        ),
        migrations.AddField(
            model_name="blockedcountry",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_countries",
                to="system_meta.product",
            ),
        ),
        migrations.AddField(
            model_name="basket",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                help_text="The tax rate assessed for this basket.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="payments.taxrate",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                help_text="The tax rate assessed for this order.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="payments.taxrate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blockedcountry",
            unique_together={("product", "country_code")},
        ),
    ]
