# Generated by Django 4.2.16 on 2024-11-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_add_blocked_country_tax_rate_update_basket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basket",
            name="user_blockable_country_code",
            field=models.CharField(
                blank=True,
                help_text="The country code for the user for this basket for blocked items.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="user_taxable_country_code",
            field=models.CharField(
                blank=True,
                help_text="The country code for the user for this basket for tax purposes.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="purchaser_blockable_country_code",
            field=models.CharField(
                blank=True,
                help_text="The country code for the user for this order for blocked items.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="purchaser_taxable_country_code",
            field=models.CharField(
                blank=True,
                help_text="The country code for the user for this order for tax purposes.",
                max_length=2,
            ),
        ),
    ]
