# Generated by Django 4.2.16 on 2024-11-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_bulkdiscountcollection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
