# Generated by Django 4.2.16 on 2024-11-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0011_alter_discount_discount_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="discount",
            name="transaction_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="discount",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="payments.company",
            ),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["company"], name="payments_di_company_11253e_idx"
            ),
        ),
    ]
