# Generated by Django 4.2.18 on 2025-02-06 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_meta", "0009_product_details_url"),
        ("payments", "0014_alter_discount_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="integrated_system",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="system_meta.integratedsystem",
            ),
        ),
    ]
