# Generated by Django 4.2.20 on 2025-03-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_create_custom_user_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="The user account is active"
            ),
        ),
    ]
