# Generated by Django 4.2.20 on 2025-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_make_users_default_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_optin",
            field=models.BooleanField(
                default=False,
                help_text="User has opted in to receive email notifications",
            ),
        ),
    ]
