FROM node:18.18.2
LABEL maintainer "ODL DevOps <mitx-devops@mit.edu>"

RUN apt-get update && apt-get install libelf1

USER node

# Workaround for ownership issues on /src
# Your user in the host system owns this directory anda corresponding user
# with the same uid doesn't exist in the container. This makes git unhappy,
# which also makes commands like `yarn run test-watch` unhappy.
RUN git config --global --add safe.directory /src
