"""
Constants for the payments app.
"""

PAYMENT_HOOK_ACTION_PRE_SALE = "presale"
PAYMENT_HOOK_ACTION_POST_SALE = "postsale"
PAYMENT_HOOK_ACTION_POST_REFUND = "postrefund"

PAYMENT_HOOK_ACTIONS = [
    PAYMENT_HOOK_ACTION_PRE_SALE,
    PAYMENT_HOOK_ACTION_POST_SALE,
    PAYMENT_HOOK_ACTION_POST_REFUND,
]

GEOLOCATION_TYPE_PROFILE = "profile"
GEOLOCATION_TYPE_GEOIP = "geoip"
GEOLOCATION_TYPE_NONE = "none"
GEOLOCATION_TYPES = [
    GEOLOCATION_TYPE_PROFILE,
    GEOLOCATION_TYPE_GEOIP,
    GEOLOCATION_TYPE_NONE,
]
GEOLOCATION_CHOICES = zip(GEOLOCATION_TYPES, GEOLOCATION_TYPES)
