# Generated by Django 4.2.8 on 2023-12-19 21:09

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegratedSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("api_key", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(help_text="SKU of the product.", max_length=255),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short name of the product, displayed in carts/etc.",
                        max_length=255,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price (decimal to two places)",
                        max_digits=7,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Long description of the product."),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Controls visibility of the product in the app.",
                    ),
                ),
                (
                    "system_data",
                    models.JSONField(
                        blank=True,
                        help_text="System-specific data for the product (in JSON).",
                        null=True,
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        help_text="Owner system of the product.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="products",
                        to="system_meta.integratedsystem",
                    ),
                ),
            ],
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("sku", "system"),
                name="unique_purchasable_sku_per_system",
            ),
        ),
    ]
