# Generated by Django 4.2.15 on 2024-09-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_meta", "0003_add_system_webhook_url_fields"),
    ]

    operations = [
        migrations.RenameField(
            model_name="integratedsystem",
            old_name="sale_succeeded_webhook_url",
            new_name="webhook_url",
        ),
        migrations.RemoveField(
            model_name="integratedsystem",
            name="sale_refunded_webhook_url",
        ),
        migrations.AlterField(
            model_name="integratedsystem",
            name="api_key",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Shared key used by the integrated system to verify "
                    "authenticity of the data sent by UE."
                ),
            ),
        ),
    ]
