# Generated by Django 4.2.16 on 2024-10-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "system_meta",
            "0004_rename_sale_succeeded_webhook_url_integratedsystem_webhook_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="integratedsystem",
            name="payment_process_redirect_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
