# Generated by Django 4.2.16 on 2024-12-02 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_meta", "0005_integratedsystem_payment_process_redirect_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegratedSystemAPIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(editable=False, max_length=8, unique=True)),
                ("hashed_key", models.CharField(editable=False, max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "revoked",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Once API key expires, clients cannot use it anymore.",
                        null=True,
                        verbose_name="Expires",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "integrated_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="system_meta.integratedsystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integrated System API Key",
                "verbose_name_plural": "Integrated System API Keys",
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
    ]
