# Generated by Django 4.2.17 on 2025-01-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_meta', '0007_product_image_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='integratedsystem',
            name='homepage_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
