# Generated by Django 4.2.17 on 2025-01-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_meta', '0008_integratedsystem_homepage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details_url',
            field=models.URLField(blank=True, default='', help_text='URL to the product details page.'),
        ),
    ]
