# Generated by Django 4.2.9 on 2024-01-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeycloakAdminToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("authorization_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True)),
                ("authorization_token_expires_in", models.IntegerField()),
                ("refresh_token_expires_in", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
