# Generated by Django 4.2.10 on 2024-03-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_add_keycloak_user_info_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keycloakadmintoken",
            name="authorization_token_expires_in",
            field=models.IntegerField(
                help_text="Seconds until authentication token expires"
            ),
        ),
        migrations.AlterField(
            model_name="keycloakadmintoken",
            name="refresh_token_expires_in",
            field=models.IntegerField(
                help_text="Seconds until refresh token expires", null=True
            ),
        ),
    ]
