# Generated by Django 4.2.11 on 2024-03-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_add_helptext_to_keycloak_token_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keycloakadmintoken",
            name="refresh_token",
            field=models.TextField(blank=True, default=""),
        ),
    ]
