apisix:
  node_listen:
    - port: ${{APISIX_PORT}}

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_listen:
      port: ${{APISIX_ADMIN_PORT}}

    allow_admin:
      - 0.0.0.0/0  # Please set it to the subnet address you obtained.
                  # If not set, by default all IP access is allowed.
    admin_key:
      - name: admin
        key: ${{APISIX_API_KEY}}
        role: admin
  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30

upstreams:
  - id: 1
    nodes:
      "nginx:8073": 1
    type: roundrobin

routes:
  - id: 1
    name: "ue-unauth"
    desc: "Unauthenticated routes, including assets and checkout callback API"
    priority: 0
    upstream_id: 1
    plugins: {}
    uris:
    - "/checkout/result"
    - "/static"
    - "/api/schema"
  - id: 2
    name: "ue-default"
    desc: "Wildcard route for the rest of the system - authentication required"
    priority: 1
    upstream_id: 1
    plugins:
      openid-connect:
        client_id: ${{KEYCLOAK_CLIENT_ID}}
        client_secret: ${{KEYCLOAK_CLIENT_SECRET}}
        discovery: ${{KEYCLOAK_DISCOVERY_URL}}
        realm: ${{KEYCLOAK_REALM}}
        scope: "openid profile"
        bearer_only: false
        introspection_endpoint_auth_method: "client_secret_post"
    uris:
    - "/*"
